// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC28nsZHm5itanFcL4zooirmseBanIXgSw',
    appId: '1:867218081496:web:b0434f947f616a321239ad',
    messagingSenderId: '867218081496',
    projectId: 'restorant-f8eff',
    authDomain: 'restorant-f8eff.firebaseapp.com',
    storageBucket: 'restorant-f8eff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBE7mzGAriiAcmPlAhymmDQR3P1-8ZxVc',
    appId: '1:867218081496:android:739df60841786a981239ad',
    messagingSenderId: '867218081496',
    projectId: 'restorant-f8eff',
    storageBucket: 'restorant-f8eff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQAiwiRjKNf5ZF4FpF8AJtUAoLgXUt0Y',
    appId: '1:867218081496:ios:bcce0549e1ae0ee81239ad',
    messagingSenderId: '867218081496',
    projectId: 'restorant-f8eff',
    storageBucket: 'restorant-f8eff.appspot.com',
    iosBundleId: 'com.example.restorant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIQAiwiRjKNf5ZF4FpF8AJtUAoLgXUt0Y',
    appId: '1:867218081496:ios:bcce0549e1ae0ee81239ad',
    messagingSenderId: '867218081496',
    projectId: 'restorant-f8eff',
    storageBucket: 'restorant-f8eff.appspot.com',
    iosBundleId: 'com.example.restorant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC28nsZHm5itanFcL4zooirmseBanIXgSw',
    appId: '1:867218081496:web:ae6523a6681955fd1239ad',
    messagingSenderId: '867218081496',
    projectId: 'restorant-f8eff',
    authDomain: 'restorant-f8eff.firebaseapp.com',
    storageBucket: 'restorant-f8eff.appspot.com',
  );
}
